# Generated by Django 5.1.1 on 2025-09-27 18:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar image should not exceed 200x200 pixels.', upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
