# Generated by Django 5.1.1 on 2025-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_auto_20200806_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
